# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
