# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_auto_20170801_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('teste', models.CharField(max_length=50)),
                ('teste1', models.CharField(max_length=100)),
            ],
        ),
    ]
