# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_auto_20170801_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
