# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0019_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('telefone', models.IntegerField(verbose_name=b'Telefone')),
                ('latitude', models.FloatField(max_length=50, verbose_name=b'Latitude')),
                ('longitude', models.FloatField(max_length=50, verbose_name=b'Longitude')),
                ('situacao', models.BooleanField(verbose_name=b'Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name=b'Tipo')),
                ('nome', models.CharField(max_length=50, verbose_name=b'Nome')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('teste1', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
    ]
