# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0023_auto_20170802_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='lojausuario',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='recebimento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='recebimentos',
            name='loja',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
        migrations.DeleteModel(
            name='LojaUsuario',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Recebimentos',
        ),
    ]
