# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0024_auto_20170802_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('situacao', models.BooleanField(verbose_name=b'Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Valor')),
                ('quantidade', models.IntegerField(verbose_name=b'Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('telefone', models.IntegerField(verbose_name=b'Telefone')),
                ('latitude', models.FloatField(max_length=50, verbose_name=b'Latitude')),
                ('longitude', models.FloatField(max_length=50, verbose_name=b'Longitude')),
                ('situacao', models.BooleanField(verbose_name=b'Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='LojaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebimento_valor', models.CharField(max_length=100, verbose_name=b'Valor')),
                ('data', models.DateField(verbose_name=b'Data')),
                ('situacao', models.BooleanField(verbose_name=b'Ativo')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Valor')),
                ('data', models.DateField(verbose_name=b'Data')),
                ('situacao', models.BooleanField(verbose_name=b'Ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Recebimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('situacao', models.BooleanField(verbose_name=b'Ativo')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name=b'Tipo')),
                ('nome', models.CharField(max_length=50, verbose_name=b'Nome')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('senha', models.CharField(max_length=6, verbose_name=b'Senha')),
                ('data', models.DateField(verbose_name=b'Data')),
                ('situacao', models.BooleanField(verbose_name=b'Ativo')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Recebimentos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usuario'),
        ),
        migrations.AddField(
            model_name='lojausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Usuario'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Pedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Produto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Loja'),
        ),
    ]
