# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0027_auto_20170814_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=b'Email'),
        ),
    ]
