# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0015_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuarioss',
        ),
    ]
