# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0016_auto_20170801_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarioss',
            new_name='Usuario',
        ),
    ]
