# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0017_auto_20170801_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
