# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0022_auto_20170802_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lojausuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
