# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0025_auto_20170802_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recebimentos',
            new_name='Recebimento',
        ),
    ]
