# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0035_auto_20171102_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='situacao',
            field=models.CharField(max_length=100, verbose_name=b'Ativo'),
        ),
    ]
