# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import sistema_pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0036_auto_20171106_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.FileField(default=b'SOME STRING', upload_to=sistema_pedidos.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='situacao',
            field=models.CharField(max_length=100, verbose_name=b'Situa\xc3\xa7\xc3\xa3o'),
        ),
    ]
