# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import sistema_pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0037_auto_20171109_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='foto',
            field=models.FileField(default=b'lojas/sem_imagem.jpg', upload_to=sistema_pedidos.models.get_file_path),
        ),
    ]
