# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0039_auto_20171109_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
    ]
