# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0041_auto_20171109_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.FileField(default=b'', max_length=1000, upload_to=b''),
        ),
    ]
